AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notion-to-google-calendar-sync

  Sample SAM Template for notion-to-google-calendar-sync

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  NotionIntegrationSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/notion-to-google-calendar-sync/prd/notion-integration-secret'
  SyncIntervalMinutes:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/notion-to-google-calendar-sync/prd/sync-interval-minutes'

Resources:
  NtGFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "notion-to-google-calendar-sync"
      CodeUri: notion-to-google-calendar-sync/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Environment:
        Variables:
          NOTION_INTEGRATION_SECRET: !Ref NotionIntegrationSecret
          SYNC_INTERVAL_MINUTES: !Ref SyncIntervalMinutes

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # NtGApi:
  #   Description: API Gateway endpoint URL for Prod stage for Hello World function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  NtGFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt NtGFunction.Arn
  NtGFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt NtGFunctionRole.Arn
